doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '13'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Entities'
                prefix: 'App\Domain\Entities'
                alias: App