# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        handler_id: null
        cookie_secure: auto
    router:
        utf8: true

