# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true

    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    router:
        resource: '%kernel.project_dir%/config/routes.yaml'
        strict_requirements: null

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
