sonata_admin:
    title: 'Sonata Admin'
    title_logo: '/path/to/logo.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        list: '@SonataAdmin/CRUD/list.html.twig'
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'

