# config/routes.yaml

# config/routes.yaml
arbitrage_index:
  path: /arbitrage
  controller: App\Infrastructure\Controllers\API\ArbitrageController::index

arbitrage_execute:
  path: /arbitrage/execute
  controller: App\Infrastructure\Controllers\API\ArbitrageController::executeArbitrage


trading_bot:
  path: /trading-bot
  controller: App\Controller\TradingBotController::index

trading_bot_run:
  path: /trading-bot/run
  controller: App\Controller\TradingBotController::run
  methods: [POST]


admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin