services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Define the GuzzleHttp\Client service
    guzzle.client:
        class: GuzzleHttp\Client
        arguments:
            - { verify: false, debug: true }

    # Define the BinanceSpotFactory
    App\Infrastructure\Factory\BinanceSpotFactory: ~

    # Define the Binance\Spot service using the factory
    Binance\Spot:
        factory: ['App\Infrastructure\Factory\BinanceSpotFactory', 'create']
        arguments:
            $key: '%env(BINANCE_API_KEY)%'
            $secret: '%env(BINANCE_SECRET_KEY)%'

    # Define TradingBotService with the correct strategy
    App\Application\Services\TradingBotService:
        arguments:
            $key: '%env(BINANCE_API_KEY)%'
            $secret: '%env(BINANCE_SECRET_KEY)%'
            $strategy: '@App\Application\Services\MovingAverageStrategy'

    # Define MovingAverageStrategy
    App\Application\Services\MovingAverageStrategy:
        arguments:
            $client: '@Binance\Spot'
