services:
    app.admin.user:
        class: App\Presentation\Controller\Admin\UserAdmin
        arguments: [ ~, App\Domain\Entities\User, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Infrastructure\Persistence\Doctrine\UserRepository:
        class: App\Infrastructure\Persistence\Doctrine\UserRepository
        arguments:
            $registry: '@doctrine'

    App\Domain\Entities\:
        resource: '../src/Domain/Entities'
        public: true
        autowire: false
        autoconfigure: false

    App\Presentation\Controller\Admin\UserAdmin:
        arguments: [ ~, App\Domain\Entities\User, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }

    # Define the GuzzleHttp\Client service
    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        arguments:
            - { verify: false }

    # Define the BinanceSpot service
    App\Infrastructure\Services\BinanceSpot:
        class: App\Infrastructure\Services\BinanceSpot
        arguments:
            $key: '%env(BINANCE_API_KEY)%'
            $secret: '%env(BINANCE_SECRET_KEY)%'
            $httpClient: '@GuzzleHttp\Client'

    # Define strategies
    App\Application\Services\MovingAverageStrategy: ~
    # Add other strategies here if needed
    # App\Application\Services\AnotherStrategy: ~

    # Define the TradingStrategyFactory
    App\Application\Factories\TradingStrategyFactory:
        arguments:
            $strategies:
                moving_average: '@App\Application\Services\MovingAverageStrategy'
                # Add other strategies here if needed
                # another_strategy: '@App\Application\Services\AnotherStrategy'

    # Define the TradingBotService with the correct strategy
    App\Application\Services\TradingBotService:
        arguments:
            $key: '%env(BINANCE_API_KEY)%'
            $secret: '%env(BINANCE_SECRET_KEY)%'
            $client: '@App\Infrastructure\Services\BinanceSpot'
            $strategy: '@App\Application\Services\MovingAverageStrategy'

    # Bind the TradingBotCommand service
    App\Presentation\Commands\TradingBotCommand:
        tags: ['console.command']
        arguments:
            $tradingBotService: '@App\Application\Services\TradingBotService'

    App\Infrastructure\Services\External\ArbitrageService:
        arguments:
            $binanceApiService: '@App\Infrastructure\Services\External\BinanceApiService'
            $logger: '@logger'
            $tradingFee: '%env(TRADING_FEE)%'

    App\Presentation\Commands\ArbitrageBotCommand:
        tags: [ 'console.command' ]
        arguments:
            $arbitrageService: '@App\Infrastructure\Services\External\ArbitrageService'

    # Utils
    App\Shared\Utils\DateFormatter: ~

    # Value Objects
    App\Domain\ValueObjects\Trading\InvestmentAmount: ~

    #Adapters
    App\Shared\Adapters\HttpClientAdapter:
        arguments:
            $client: '@GuzzleHttp\Client'

    App\Infrastructure\Security\AdminAccessVoter:
        tags:
            - { name: security.voter }

    App\Infrastructure\Services\External\BinanceApiService:
        arguments:
            $apiKey: '%env(BINANCE_API_KEY)%'
            $apiSecret: '%env(BINANCE_SECRET_KEY)%'

    App\Infrastructure\Services\External\CoinbaseApiService:
        arguments:
            $client: '@http_client'





